### ISSUE TITLE
So i cant install the texture could you tell me how to?

### ISSUE THREAD

**Issue by dhairya-mistry** [CloneyInnit/LarryPack#1]

**Comment by dhairya-mistry** [comment]
Cloney or someone pls help me

**Comment by lumi-nation** [comment]
1. you download the pack
2. go in your resource pack files (if you don't know how you go in your game. Resource Pack > Open Pack Folder)
3. and paste it in it

if it doesn't work tell me more

**Comment by CloneyInnit** [comment]
Go to:
https://github.com/CloneyInnit/LarryPack/releases
and download the .zip file

Then head to your Minecraft resourcepacks folder, and drop it there.

**Comment by lumi-nation** [comment]
It works too
